### ISSUE TITLE
Compilation for Windows and Python 3.10

### ISSUE THREAD

**Issue by charlesneimog** [gesellkammer/vamphost#2]
Hi,
Could you please add this `wheel` to the pip?

On Windows, the actual wheel does not install. It is related to this https://github.com/davisking/dlib/issues/2463#issuecomment-976756345

[dist.zip](https://github.com/gesellkammer/vamphost/files/9543696/dist.zip)

I add the:

``` c++
#if defined(_MSC_VER)
#  pragma warning(push)
#  pragma warning(disable: 4127) // warning C4127: Conditional expression is constant
#include <BaseTsd.h>
typedef SSIZE_T ssize_t;
#endif

```
In `.h` of numpy.

Thanks for the work!

**Comment by gesellkammer** [comment]
I don't quite follow. The issue you are referring to is related to pybind and python 3.10. vamphost does not use pybind and at the moment we do not provide a wheel for python 3.10. 

Please provide: os, python version, error, etc.

**Comment by gesellkammer** [comment]
ok, this is fixed now. There are window wheels for python 3.10, please test them and confirm that they work on your system.

**Comment by charlesneimog** [comment]
Hi, sorry. 

The problem is with numpy. 

But your fix work here, thank you very much!
